services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/app
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - mynetwork
    depends_on:
      - nodejs

  nodejs:
    image: node:18
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
#    command: sh -c "npm install && npm run typeorm:run && npm run fill-db && npm run test && npm run start"
    command: "npm run typeorm:run & npm run test & npm start"
    environment:
      - DATABASE_TYPE=$${env.DATABASE_TYPE}
      - DATABASE_HOST=$${env.DATABASE_HOST}
      - DATABASE_PORT=$${env.DATABASE_PORT}
      - DATABASE_USERNAME=$${env.DATABASE_USERNAME}
      - DATABASE_PASSWORD=$${env.DATABASE_PASSWORD}
      - DATABASE_NAME=$${env.DATABASE_NAME}
      - ACCESS_KEY_ID=$${env.ACCESS_KEY_ID}
      - SECRET_ACCESS_KEY=$${env.SECRET_ACCESS_KEY}
      - REGION=$${env.REGION}
      - BUCKET=$${env.BUCKET}
      - JWT_SECRET=$${env.JWT_SECRET}
      - SERVER_PORT=$${env.SERVER_PORT}
    networks:
      - mynetwork

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Zaq1W2e34Zsq21waX
      MYSQL_DATABASE: star_wars
      MYSQL_USER: admin
      MYSQL_PASSWORD: Zaq1W2e34
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
