services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/app
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - mynetwork
    depends_on:
      - nodejs

  nodejs:
    image: node:18
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    #    command: sh -c "npm install && npm run typeorm:run && npm run fill-db && npm run start"
    command: sh -c "npm install && npm run typeorm:run && npm run test && npm run start"
    environment:
      DATABASE_TYPE: "${DATABASE_TYPE}"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_PORT: "${DATABASE_PORT}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_NAME: "${DATABASE_NAME}"
      ACCESS_KEY_ID: "${ACCESS_KEY_ID}"
      SECRET_ACCESS_KEY: "${SECRET_ACCESS_KEY}"
      REGION: "${REGION}"
      BUCKET: "${BUCKET}"
      JWT_SECRET: "${JWT_SECRET}"
      SERVER_PORT: "${SERVER_PORT}"
    networks:
      - mynetwork
    depends_on:
      - zabbix-agent

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Zaq1W2e34Zsq21waX
      MYSQL_DATABASE: star_wars
      MYSQL_USER: admin
      MYSQL_PASSWORD: Zaq1W2e34
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: admin
      MYSQL_PASSWORD: Zaq1W2e34
      MYSQL_ROOT_PASSWORD: Zaq1W2e34Zsq21waX
    depends_on:
      - mysql
    ports:
      - "10051:10051"
    networks:
      - mynetwork

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: admin
      MYSQL_PASSWORD: Zaq1W2e34
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Moscow
    depends_on:
      - zabbix-server
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: "nodejs"
    networks:
      - mynetwork
    depends_on:
      - zabbix-server

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
